import { AssistantTool } from './assistant.interface';
import { ModelInfo } from './model.interface';

export interface Thread {
  /** Unique identifier for the thread, generated by default using the ULID method. **/
  id: string;

  /** Object name **/
  object: string;

  /** The title of this thread. **/
  title: string;

  /** Assistants in this thread. **/
  assistants: ThreadAssistantInfo[];

  /** The timestamp indicating when this thread was created, represented in ISO 8601 format. **/
  createdAt: number;

  /** The timestamp indicating when this thread was updated, represented in ISO 8601 format. **/
  updatedAt?: number;

  /**
   * The additional metadata of this thread.
   **/
  metadata?: ThreadMetadata;
}

export interface ThreadMetadata {
  lastMessage?: string;
}

/**
 * Represents the information about an assistant in a thread.
 * @stored
 */
export interface ThreadAssistantInfo {
  assistant_id: string;
  assistant_name: string;
  model: ModelInfo;
  instructions?: string;
  tools?: AssistantTool[];
}
