export interface IThread {
  /** Unique identifier for the thread, generated by default using the ULID method. **/
  id: string;

  /** Object name **/
  object: string;

  /** The title of this thread. **/
  title: string;

  /** Assistants in this thread. **/
  //assistants: ThreadAssistantInfo[];

  /** The timestamp indicating when this thread was created, represented in ISO 8601 format. **/
  createdAt: number;

  /** The timestamp indicating when this thread was updated, represented in ISO 8601 format. **/
  updatedAt?: number;

  /** The additional metadata of this thread. **/
  metadata?: string; //Record<string, unknown>;
}
