import { IThread } from 'src/core/interfaces/thread.interface';
import { Entity, PrimaryColumn, Column } from 'typeorm';

// this should be a DTO
@Entity('threads')
export class Thread implements IThread {
  /**
   * Unique identifier for the thread, generated by default using the ULID method.
   **/
  @PrimaryColumn()
  id: string;

  @Column()
  object: string;

  /** The title of this thread. **/
  @Column({ name: 'title' })
  title: string;

  /** Assistants in this thread. **/
  // TODO: NamH implement this
  //assistants: ThreadAssistantInfo[];

  /** The timestamp indicating when this thread was created, represented in ISO 8601 format. **/
  @Column()
  createdAt: number;

  /**
   * The timestamp indicating when this thread was updated, represented in ISO 8601 format.
   **/
  @Column({ nullable: true })
  updatedAt?: number;

  /**
   * The additional metadata of this thread.
   **/
  @Column({ nullable: true })
  metadata?: string;
}
