import { ApiProperty } from '@nestjs/swagger';
import { UsageDto } from './usage.dto';
import { ChoiceDto } from './choice.dto';

export class ChatCompletionResponseDto {
  @ApiProperty({
    description: "A list of choices generated by the chat model.",
    type: [ChoiceDto]
  })
  choices: ChoiceDto[];
  
  @ApiProperty({
    description: "The timestamp of when the chat completion was created, expressed as a Unix timestamp.",
    type: Number
  })
  created: number;
  
  @ApiProperty({
    description: "The unique identifier for the chat completion.",
    type: String
  })
  id: string;
  
  @ApiProperty({
    description: "The identifier of the model used to generate the chat completion.",
    type: String
  })
  model: string;
  
  @ApiProperty({
    description: "The type of object, typically set to 'chat_completion' to denote the nature of the API response.",
    type: String
  })
  object: string;
  
  @ApiProperty({
    description: "A unique fingerprint that identifies the system configuration used during the chat completion.",
    type: String
  })
  system_fingerprint: string;
  
  @ApiProperty({
    description: "An object representing the usage statistics of the model for the current completion.",
    type: UsageDto
  })
  usage: UsageDto;
  
}
