import { ApiProperty } from '@nestjs/swagger';

export class MessageDto {
  @ApiProperty({
    description:
      'The textual content of the chat message or completion generated by the model.',
    type: String,
  })
  content: string;

  @ApiProperty({
    description:
      "The role of the participant in the chat, such as 'user' or 'system', indicating who is the sender of the message.",
    type: String,
  })
  role: string;
}
