import { ApiProperty } from '@nestjs/swagger';

export class UsageDto {
  @ApiProperty({
    description: "The number of tokens used in the completion part of the response generated by the model.",
    type: Number
  })
  completion_tokens: number;
  
  @ApiProperty({
    description: "The number of tokens used in the prompt part of the chat input, which is provided to the model.",
    type: Number
  })
  prompt_tokens: number;
  
  @ApiProperty({
    description: "The total number of tokens used in both the prompt and the completion, summarizing the entire token count of the chat operation.",
    type: Number
  })
  total_tokens: number;
  
}
